# Generated by Django 4.1.4 on 2022-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
